### PR TITLE
Added functions to the app

### PR DESCRIPTION
**Pull request by louiCoder**
please help me review my code. thx!  @leni1 @King-Benx  @tricias260 @pktahinduka @ongwech . i will be waiting on your replies. thx again

### CODE REVIEW

**Comment by louiCoder** [comment]
here's the direct link to the file for reviewing. 

https://goo.gl/1hGy7Q

**Comment by louiCoder** [comment]
@hariclerry please help me review here..thx

**Comment by leni1** [comment]
@louiCoder Looks good to me, though I wonder why the global variables. I don't know what your LFA thinks, but it is generally advised not to use them. If you're sure they suit your use case and you can't find an alternative, then to me the code looks solid.

**Comment by louiCoder** [comment]
thanx alot for the feedback @leni1 . the global variables are for my testing purposes. But in case i need to change them i will do that

**Pull request merged**
