### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by louiCoder**
please help me review my code. i will be waiting on your feedback if any changes are required. @tricias260 @King-Benx @leni1

### CODE REVIEW

**Comment by King-Benx** [comment]
Site looks fine, good work

**Comment by tricias260** [comment]
@louiCoder, site looks fine up to this stage. Cudos!

**Comment by leni1** [comment]
@louiCoder Looks good to me, though you need to remove the placeholder text that's presently on the Login Page. Other than that, well done.

**Comment by louiCoder** [comment]
@leni1 noted! i will remove that and just leave the login form only. Thx @King-Benx for your feedback. Thx @tricias260 for reviewing my code. much appreciated folks!

**Comment by louiCoder** [comment]
@leni1 this has been fixed https://github.com/louiCoder/WeConnect/commit/9197b853f77f5dca20e5acdb4480eafb6f13e73e

**Pull request merged**
